version: '3.8'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - qdrant
    environment:
      QDRANT_HOST: qdrant

  qdrant:
    image: "qdrant/qdrant"
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
volumes:
  qdrant-data:
